### ISSUE TITLE
Update 2022 PDFs

### ISSUE THREAD

**Issue by vukosim** [dsfsi/vukuzenzele-nlp#15]
#### Description
Fetch latest 2022 PDFs up to December 2022

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Go to vukuzenzele website
- [ ] Download missing pdfs for 2022 add to repo in raw
- [ ] Commit, create pull request

**Comment by vukosim** [comment]
Hey @AndaniMadodonga, can you assist with finishing this.
