### ISSUE TITLE
Sentence Alignment

### ISSUE THREAD

**Issue by lastrucci01** [dsfsi/vukuzenzele-nlp#16]
#### Description
Perform sentence alignment on the data/processed folder using LASER sentence embedders 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [X] Clean/preprocess data and write to .txt
- [X] Perform sentence embeddings to produce sentence vectors
- [X] Align sentences using above vectors

- [X]  Automation of this process

**Comment by lastrucci01** [comment]
#### Problems
Currently the only problem I am facing is not being able to download imports needed by LASER.
This is due to my version of Python and/or my computer architecture. 

#### Workaround
I am using Docker to be able to run the code to perfom embedding using a friendly python version and runtime env.
Hopefully I can achieve a similar situation with a github action.

**Comment by lastrucci01** [comment]
#### Serious Problem

@vukosim 

Unfortunately, I cannot find a workaround for the following error:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/100759852/213787694-a71267de-bab7-4e95-8ff3-8a564c403ba2.png">

Fairseq is a module used by LASER. I cannot install the correct version for it. @Zenthon miraculously managed to get the right runtime env (ubuntu20.04.5 & python3.8.10) to get it working and I tried replicating it on docker but the error persists.

I have yet to find a workaround but worst comes to worst I guess Ishe can test my code...

**Comment by lastrucci01** [comment]
Thankfully Ishe did the embeddings for me and I continued from there, this issue can be closed through PR #19
