### ISSUE TITLE
Incorrect formatting of the final versions of files

### ISSUE THREAD

**Issue by vukosim** [dsfsi/vukuzenzele-nlp#22]
#### Description
We have a template of how e want the processed files to look like. @PKhoboko you have submitted incorrect formats. See below screenshots
#### Screenshots
Incorrect
![image](https://user-images.githubusercontent.com/836223/234266008-9de900ce-683d-4721-a527-b2c7fe101cd4.png)
* Not cleaned
* Non removal of irrelavant text
* does not use our structure
* Please see the initial email we sent you with instructions.

Correct
![image](https://user-images.githubusercontent.com/836223/234265866-c5b80c32-d681-43ca-8fdb-2486923f71e6.png)

#### Files
[Your file
](https://github.com/dsfsi/vukuzenzele-nlp/blob/master/data/processed/2019-01-ed1/2019-01-ed1-vukuzenzele-eng-02.txt)

[Proper formatting 
](https://github.com/dsfsi/vukuzenzele-nlp/blob/master/data/processed/2021-09-ed1/2021-09-ed1-vukuzenzele-eng-002.txt)#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Fix all submitted files by 12 May 2023
- [ ] Use git tool pull and push to github (create a branch to fix, then do a merge request)
- [ ] Naming of files correct.
